name: Sync to Hugging Face Space

on:
  push:
    branches: [main, master]
  workflow_dispatch:  # Allow manual triggering

jobs:
  sync-to-huggingface:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install huggingface_hub requests

      - name: Test Hugging Face API Access
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
          HF_USERNAME: ${{ secrets.HF_USERNAME }}
        run: |
          python -c "
          import os, sys, requests
          token = os.environ.get('HF_TOKEN')
          username = os.environ.get('HF_USERNAME')
          
          if not token or not username:
              print('Error: HF_TOKEN and HF_USERNAME must be set')
              sys.exit(1)
              
          print(f'Testing API access for user: {username}')
          
          # Only show parts of token for security
          token_prefix = token[:4] if len(token) > 8 else '****'
          token_suffix = token[-4:] if len(token) > 8 else '****'
          print(f'Using token: {token_prefix}...{token_suffix}')
          
          try:
              response = requests.get(
                  'https://huggingface.co/api/whoami',
                  headers={'Authorization': f'Bearer {token}'}
              )
              
              print(f'API Status code: {response.status_code}')
              
              if response.status_code == 200:
                  print('Authentication successful!')
                  print(f'User info: {response.json()}')
              else:
                  print(f'Authentication failed. Response: {response.text}')
                  sys.exit(1)
          except Exception as e:
              print(f'Error: {e}')
              sys.exit(1)
          "

      # Create/update the Hugging Face Space
      - name: Create/Update Hugging Face Space
        id: create_space
        uses: huggingface/huggingface-spaces@main
        with:
          # Required
          name: ${{ github.event.repository.name }}
          token: ${{ secrets.HF_TOKEN }}
          # Optional
          space_sdk: streamlit
          sdk_version: 1.43.2
          python_version: 3.10
          hardware: cpu-basic
          repo_type: space
          cache-examples: true
          deploy: true
          secrets: |
            EMAIL_SECRET=${{ secrets.EMAIL_SECRET }}
            GOOGLE_CLIENT_SECRET=${{ secrets.GOOGLE_CLIENT_SECRET }}

      - name: Display Space URL
        run: |
          echo "Hugging Face Space URL: https://huggingface.co/spaces/${{ secrets.HF_USERNAME }}/${{ github.event.repository.name }}" 